import type { Metadata } from "next";
import { Inter } from "next/font/google";

import {
  APP_NAME,
  APP_VERSION,
  GITHUB_ORG_URL,
  GITHUB_RELEASES_URL,
  SITE_URL,
  TEAM_NAME,
} from "@/lib/constants";

import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: {
    default: `${APP_NAME} \u2014 Streamline Your Chaos Recipe Gains`,
    template: `%s | ${APP_NAME}`,
  },
  description:
    "Free, open-source overlay tool for Path of Exile. Track chaos, regal, exalted & chance recipes in real-time. Smart stash tab overlays with pick-order highlighting. Automatic loot filter manipulation. Works with PoE 1.",
  metadataBase: new URL(SITE_URL),
  keywords: [
    "Path of Exile",
    "PoE",
    "chaos recipe",
    "chaos orb recipe",
    "regal recipe",
    "exalted recipe",
    "chance recipe",
    "recipe tracker",
    "stash overlay",
    "loot filter",
    "PoE overlay",
    "PoE tool",
    "league start",
    "currency farming",
    APP_NAME,
    "CRE",
  ],
  authors: [{ name: TEAM_NAME }],
  creator: TEAM_NAME,
  publisher: TEAM_NAME,
  applicationName: APP_NAME,
  category: "Gaming Tools",
  openGraph: {
    title: APP_NAME,
    description:
      "Streamline your Chaos Recipe gains. Free, open-source overlay tool for Path of Exile — track recipes, smart stash overlays, and automatic loot filter manipulation.",
    url: SITE_URL,
    siteName: APP_NAME,
    // OG image is auto-generated by opengraph-image.tsx — no manual `images` array needed
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: APP_NAME,
    description:
      "Streamline your Chaos Recipe gains. Free, open-source overlay for Path of Exile.",
    // Twitter image is also auto-populated from opengraph-image.tsx
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  alternates: {
    canonical: SITE_URL,
  },
  other: {
    "msapplication-TileColor": "#141414",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "SoftwareApplication",
    name: APP_NAME,
    applicationCategory: "GameApplication",
    operatingSystem: "Windows 10, Windows 11",
    offers: {
      "@type": "Offer",
      price: "0",
      priceCurrency: "USD",
    },
    description:
      "Free, open-source overlay tool for Path of Exile. Track chaos, regal, exalted & chance recipes. Smart stash overlays. Automatic loot filter manipulation.",
    url: SITE_URL,
    downloadUrl: GITHUB_RELEASES_URL,
    softwareVersion: APP_VERSION,
    author: {
      "@type": "Organization",
      name: TEAM_NAME,
      url: GITHUB_ORG_URL,
    },
    license: "https://www.gnu.org/licenses/gpl-3.0.html",
    isAccessibleForFree: true,
    screenshot: `${SITE_URL}/images/main-overlay.png`,
  };

  return (
    <html className="dark" lang="en">
      <body className={`${inter.variable} font-sans`}>
        <script
          // biome-ignore lint/security/noDangerouslySetInnerHtml: JSON-LD structured data requires dangerouslySetInnerHTML
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
          type="application/ld+json"
        />
        {children}
      </body>
    </html>
  );
}
