import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: {
    default: "Chaos Recipe Enhancer — Streamline Your Chaos Recipe Gains",
    template: "%s | Chaos Recipe Enhancer",
  },
  description:
    "Free, open-source overlay tool for Path of Exile. Track chaos, regal, exalted & chance recipes in real-time. Smart stash tab overlays with pick-order highlighting. Automatic loot filter manipulation. Works with PoE 1.",
  metadataBase: new URL("https://chaos-recipe.com"),
  keywords: [
    "Path of Exile",
    "PoE",
    "chaos recipe",
    "chaos orb recipe",
    "regal recipe",
    "exalted recipe",
    "chance recipe",
    "recipe tracker",
    "stash overlay",
    "loot filter",
    "PoE overlay",
    "PoE tool",
    "league start",
    "currency farming",
    "Chaos Recipe Enhancer",
    "CRE",
  ],
  authors: [{ name: "Chaos Recipe Enhancer Team" }],
  creator: "Chaos Recipe Enhancer Team",
  publisher: "Chaos Recipe Enhancer Team",
  applicationName: "Chaos Recipe Enhancer",
  category: "Gaming Tools",
  openGraph: {
    title: "Chaos Recipe Enhancer",
    description:
      "Streamline your Chaos Recipe gains. Free, open-source overlay tool for Path of Exile — track recipes, smart stash overlays, and automatic loot filter manipulation.",
    url: "https://chaos-recipe.com",
    siteName: "Chaos Recipe Enhancer",
    // OG image is auto-generated by opengraph-image.tsx — no manual `images` array needed
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Chaos Recipe Enhancer",
    description:
      "Streamline your Chaos Recipe gains. Free, open-source overlay for Path of Exile.",
    // Twitter image is also auto-populated from opengraph-image.tsx
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  alternates: {
    canonical: "https://chaos-recipe.com",
  },
  other: {
    "msapplication-TileColor": "#141414",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "SoftwareApplication",
    name: "Chaos Recipe Enhancer",
    applicationCategory: "GameApplication",
    operatingSystem: "Windows 10, Windows 11",
    offers: {
      "@type": "Offer",
      price: "0",
      priceCurrency: "USD",
    },
    description:
      "Free, open-source overlay tool for Path of Exile. Track chaos, regal, exalted & chance recipes. Smart stash overlays. Automatic loot filter manipulation.",
    url: "https://chaos-recipe.com",
    downloadUrl:
      "https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/releases",
    softwareVersion: "3.28",
    author: {
      "@type": "Organization",
      name: "Chaos Recipe Enhancer Team",
      url: "https://github.com/ChaosRecipeEnhancer",
    },
    license: "https://www.gnu.org/licenses/gpl-3.0.html",
    isAccessibleForFree: true,
    screenshot: "https://chaos-recipe.com/images/main-overlay.png",
  };

  return (
    <html className="dark" lang="en">
      <body className={`${inter.variable} font-sans`}>
        <script
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
          type="application/ld+json"
        />
        {children}
      </body>
    </html>
  );
}
