//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChaosRecipeEnhancer.UI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PathOfExileAccountName {
            get {
                return ((string)(this["PathOfExileAccountName"]));
            }
            set {
                this["PathOfExileAccountName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PathOfExileWebsiteSessionId {
            get {
                return ((string)(this["PathOfExileWebsiteSessionId"]));
            }
            set {
                this["PathOfExileWebsiteSessionId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LeagueName {
            get {
                return ((string)(this["LeagueName"]));
            }
            set {
                this["LeagueName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CustomLeagueEnabled {
            get {
                return ((bool)(this["CustomLeagueEnabled"]));
            }
            set {
                this["CustomLeagueEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DoNotPreserveLowItemLevelGear {
            get {
                return ((bool)(this["DoNotPreserveLowItemLevelGear"]));
            }
            set {
                this["DoNotPreserveLowItemLevelGear"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncludeIdentifiedItemsEnabled {
            get {
                return ((bool)(this["IncludeIdentifiedItemsEnabled"]));
            }
            set {
                this["IncludeIdentifiedItemsEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ChaosRecipeTrackingEnabled {
            get {
                return ((bool)(this["ChaosRecipeTrackingEnabled"]));
            }
            set {
                this["ChaosRecipeTrackingEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RegalRecipeTrackingEnabled {
            get {
                return ((bool)(this["RegalRecipeTrackingEnabled"]));
            }
            set {
                this["RegalRecipeTrackingEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExaltedShardRecipeTrackingEnabled {
            get {
                return ((bool)(this["ExaltedShardRecipeTrackingEnabled"]));
            }
            set {
                this["ExaltedShardRecipeTrackingEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FullSetThreshold {
            get {
                return ((int)(this["FullSetThreshold"]));
            }
            set {
                this["FullSetThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TargetStash {
            get {
                return ((int)(this["TargetStash"]));
            }
            set {
                this["TargetStash"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int StashTabQueryMode {
            get {
                return ((int)(this["StashTabQueryMode"]));
            }
            set {
                this["StashTabQueryMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string StashTabIndices {
            get {
                return ((string)(this["StashTabIndices"]));
            }
            set {
                this["StashTabIndices"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StashFolderName {
            get {
                return ((string)(this["StashFolderName"]));
            }
            set {
                this["StashFolderName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StashTabPrefix {
            get {
                return ((string)(this["StashTabPrefix"]));
            }
            set {
                this["StashTabPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StashTabSuffix {
            get {
                return ((string)(this["StashTabSuffix"]));
            }
            set {
                this["StashTabSuffix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoFetchOnRezoneEnabled {
            get {
                return ((bool)(this["AutoFetchOnRezoneEnabled"]));
            }
            set {
                this["AutoFetchOnRezoneEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PathOfExileClientLogLocation {
            get {
                return ((string)(this["PathOfExileClientLogLocation"]));
            }
            set {
                this["PathOfExileClientLogLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Language {
            get {
                return ((int)(this["Language"]));
            }
            set {
                this["Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CloseToTrayEnabled {
            get {
                return ((bool)(this["CloseToTrayEnabled"]));
            }
            set {
                this["CloseToTrayEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("< not set >")]
        public string FetchStashHotkey {
            get {
                return ((string)(this["FetchStashHotkey"]));
            }
            set {
                this["FetchStashHotkey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("< not set >")]
        public string ToggleSetTrackerOverlayHotkey {
            get {
                return ((string)(this["ToggleSetTrackerOverlayHotkey"]));
            }
            set {
                this["ToggleSetTrackerOverlayHotkey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("< not set >")]
        public string ToggleStashTabOverlayHotkey {
            get {
                return ((string)(this["ToggleStashTabOverlayHotkey"]));
            }
            set {
                this["ToggleStashTabOverlayHotkey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SoundEnabled {
            get {
                return ((bool)(this["SoundEnabled"]));
            }
            set {
                this["SoundEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int Volume {
            get {
                return ((int)(this["Volume"]));
            }
            set {
                this["Volume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default Sound")]
        public string ItemSetCompletedSoundFileLocation {
            get {
                return ((string)(this["ItemSetCompletedSoundFileLocation"]));
            }
            set {
                this["ItemSetCompletedSoundFileLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default Sound")]
        public string FilterModificationPendingSoundFileLocation {
            get {
                return ((string)(this["FilterModificationPendingSoundFileLocation"]));
            }
            set {
                this["FilterModificationPendingSoundFileLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SetTrackerOverlayDisplayMode {
            get {
                return ((int)(this["SetTrackerOverlayDisplayMode"]));
            }
            set {
                this["SetTrackerOverlayDisplayMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float SetTrackerOverlayOpacity {
            get {
                return ((float)(this["SetTrackerOverlayOpacity"]));
            }
            set {
                this["SetTrackerOverlayOpacity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SetTrackerOverlayItemCounterDisplayMode {
            get {
                return ((int)(this["SetTrackerOverlayItemCounterDisplayMode"]));
            }
            set {
                this["SetTrackerOverlayItemCounterDisplayMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SetTrackerOverlayOverlayLockPositionEnabled {
            get {
                return ((bool)(this["SetTrackerOverlayOverlayLockPositionEnabled"]));
            }
            set {
                this["SetTrackerOverlayOverlayLockPositionEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float StashTabOverlayOpacity {
            get {
                return ((float)(this["StashTabOverlayOpacity"]));
            }
            set {
                this["StashTabOverlayOpacity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#14FFFFFF")]
        public string StashTabOverlayBackgroundColor {
            get {
                return ((string)(this["StashTabOverlayBackgroundColor"]));
            }
            set {
                this["StashTabOverlayBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int StashTabOverlayHighlightMode {
            get {
                return ((int)(this["StashTabOverlayHighlightMode"]));
            }
            set {
                this["StashTabOverlayHighlightMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#96F90000")]
        public string StashTabOverlayHighlightColor {
            get {
                return ((string)(this["StashTabOverlayHighlightColor"]));
            }
            set {
                this["StashTabOverlayHighlightColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("23")]
        public double StashTabOverlayIndividualTabMargin {
            get {
                return ((double)(this["StashTabOverlayIndividualTabMargin"]));
            }
            set {
                this["StashTabOverlayIndividualTabMargin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20.4")]
        public double StashTabOverlayIndividualTabHeaderWidth {
            get {
                return ((double)(this["StashTabOverlayIndividualTabHeaderWidth"]));
            }
            set {
                this["StashTabOverlayIndividualTabHeaderWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double StashTabOverlayIndividualTabHeaderGap {
            get {
                return ((double)(this["StashTabOverlayIndividualTabHeaderGap"]));
            }
            set {
                this["StashTabOverlayIndividualTabHeaderGap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LootFilterManipulationEnabled {
            get {
                return ((bool)(this["LootFilterManipulationEnabled"]));
            }
            set {
                this["LootFilterManipulationEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LootFilterFileLocation {
            get {
                return ((string)(this["LootFilterFileLocation"]));
            }
            set {
                this["LootFilterFileLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LootFilterIconsEnabled {
            get {
                return ((bool)(this["LootFilterIconsEnabled"]));
            }
            set {
                this["LootFilterIconsEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF0303")]
        public string LootFilterRingColor {
            get {
                return ((string)(this["LootFilterRingColor"]));
            }
            set {
                this["LootFilterRingColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF0303")]
        public string LootFilterAmuletColor {
            get {
                return ((string)(this["LootFilterAmuletColor"]));
            }
            set {
                this["LootFilterAmuletColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF0303")]
        public string LootFilterBeltColor {
            get {
                return ((string)(this["LootFilterBeltColor"]));
            }
            set {
                this["LootFilterBeltColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF0018FF")]
        public string LootFilterBootsColor {
            get {
                return ((string)(this["LootFilterBootsColor"]));
            }
            set {
                this["LootFilterBootsColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF04FF00")]
        public string LootFilterGlovesColor {
            get {
                return ((string)(this["LootFilterGlovesColor"]));
            }
            set {
                this["LootFilterGlovesColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFF8FF04")]
        public string LootFilterHelmetColor {
            get {
                return ((string)(this["LootFilterHelmetColor"]));
            }
            set {
                this["LootFilterHelmetColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFDD00FF")]
        public string LootFilterBodyArmourColor {
            get {
                return ((string)(this["LootFilterBodyArmourColor"]));
            }
            set {
                this["LootFilterBodyArmourColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF00DCFF")]
        public string LootFilterWeaponColor {
            get {
                return ((string)(this["LootFilterWeaponColor"]));
            }
            set {
                this["LootFilterWeaponColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LootFilterRingsAlwaysActive {
            get {
                return ((bool)(this["LootFilterRingsAlwaysActive"]));
            }
            set {
                this["LootFilterRingsAlwaysActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LootFilterAmuletsAlwaysActive {
            get {
                return ((bool)(this["LootFilterAmuletsAlwaysActive"]));
            }
            set {
                this["LootFilterAmuletsAlwaysActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LootFilterBeltsAlwaysActive {
            get {
                return ((bool)(this["LootFilterBeltsAlwaysActive"]));
            }
            set {
                this["LootFilterBeltsAlwaysActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LootFilterBootsAlwaysActive {
            get {
                return ((bool)(this["LootFilterBootsAlwaysActive"]));
            }
            set {
                this["LootFilterBootsAlwaysActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LootFilterGlovesAlwaysActive {
            get {
                return ((bool)(this["LootFilterGlovesAlwaysActive"]));
            }
            set {
                this["LootFilterGlovesAlwaysActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LootFilterHelmetsAlwaysActive {
            get {
                return ((bool)(this["LootFilterHelmetsAlwaysActive"]));
            }
            set {
                this["LootFilterHelmetsAlwaysActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LootFilterBodyArmourAlwaysActive {
            get {
                return ((bool)(this["LootFilterBodyArmourAlwaysActive"]));
            }
            set {
                this["LootFilterBodyArmourAlwaysActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LootFilterWeaponsAlwaysActive {
            get {
                return ((bool)(this["LootFilterWeaponsAlwaysActive"]));
            }
            set {
                this["LootFilterWeaponsAlwaysActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double SettingsWindowTopPosition {
            get {
                return ((double)(this["SettingsWindowTopPosition"]));
            }
            set {
                this["SettingsWindowTopPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double SettingsWindowLeftPosition {
            get {
                return ((double)(this["SettingsWindowLeftPosition"]));
            }
            set {
                this["SettingsWindowLeftPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double SetTrackerOverlayTopPosition {
            get {
                return ((double)(this["SetTrackerOverlayTopPosition"]));
            }
            set {
                this["SetTrackerOverlayTopPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double SetTrackerOverlayLeftPosition {
            get {
                return ((double)(this["SetTrackerOverlayLeftPosition"]));
            }
            set {
                this["SetTrackerOverlayLeftPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("74")]
        public double StashTabOverlayTopPosition {
            get {
                return ((double)(this["StashTabOverlayTopPosition"]));
            }
            set {
                this["StashTabOverlayTopPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public double StashTabOverlayLeftPosition {
            get {
                return ((double)(this["StashTabOverlayLeftPosition"]));
            }
            set {
                this["StashTabOverlayLeftPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("690")]
        public double StashTabOverlayHeight {
            get {
                return ((double)(this["StashTabOverlayHeight"]));
            }
            set {
                this["StashTabOverlayHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("641")]
        public double StashTabOverlayWidth {
            get {
                return ((double)(this["StashTabOverlayWidth"]));
            }
            set {
                this["StashTabOverlayWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DebugMode {
            get {
                return ((bool)(this["DebugMode"]));
            }
            set {
                this["DebugMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpgradeSettingsAfterUpdate {
            get {
                return ((bool)(this["UpgradeSettingsAfterUpdate"]));
            }
            set {
                this["UpgradeSettingsAfterUpdate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SelectedStashTabName {
            get {
                return ((string)(this["SelectedStashTabName"]));
            }
            set {
                this["SelectedStashTabName"] = value;
            }
        }
    }
}
