//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChaosRecipeEnhancer.UI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PathOfExileAccountName {
            get {
                return ((string)(this["PathOfExileAccountName"]));
            }
            set {
                this["PathOfExileAccountName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PoEAccountConnectionStatus {
            get {
                return ((int)(this["PoEAccountConnectionStatus"]));
            }
            set {
                this["PoEAccountConnectionStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ChaosRecipeTrackingEnabled {
            get {
                return ((bool)(this["ChaosRecipeTrackingEnabled"]));
            }
            set {
                this["ChaosRecipeTrackingEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncludeIdentifiedItemsEnabled {
            get {
                return ((bool)(this["IncludeIdentifiedItemsEnabled"]));
            }
            set {
                this["IncludeIdentifiedItemsEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int FullSetThreshold {
            get {
                return ((int)(this["FullSetThreshold"]));
            }
            set {
                this["FullSetThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Standard")]
        public string LeagueName {
            get {
                return ((string)(this["LeagueName"]));
            }
            set {
                this["LeagueName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int StashTabQueryMode {
            get {
                return ((int)(this["StashTabQueryMode"]));
            }
            set {
                this["StashTabQueryMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StashTabPrefix {
            get {
                return ((string)(this["StashTabPrefix"]));
            }
            set {
                this["StashTabPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoFetchOnRezoneEnabled {
            get {
                return ((bool)(this["AutoFetchOnRezoneEnabled"]));
            }
            set {
                this["AutoFetchOnRezoneEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PathOfExileClientLogLocation {
            get {
                return ((string)(this["PathOfExileClientLogLocation"]));
            }
            set {
                this["PathOfExileClientLogLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SetTrackerOverlayItemCounterDisplayMode {
            get {
                return ((int)(this["SetTrackerOverlayItemCounterDisplayMode"]));
            }
            set {
                this["SetTrackerOverlayItemCounterDisplayMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SetTrackerOverlayDisplayMode {
            get {
                return ((int)(this["SetTrackerOverlayDisplayMode"]));
            }
            set {
                this["SetTrackerOverlayDisplayMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SetTrackerOverlayOverlayLockPositionEnabled {
            get {
                return ((bool)(this["SetTrackerOverlayOverlayLockPositionEnabled"]));
            }
            set {
                this["SetTrackerOverlayOverlayLockPositionEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float StashTabOverlayOpacity {
            get {
                return ((float)(this["StashTabOverlayOpacity"]));
            }
            set {
                this["StashTabOverlayOpacity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#14FFFFFF")]
        public string StashTabOverlayBackgroundColor {
            get {
                return ((string)(this["StashTabOverlayBackgroundColor"]));
            }
            set {
                this["StashTabOverlayBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#96F90000")]
        public string StashTabOverlayHighlightColor {
            get {
                return ((string)(this["StashTabOverlayHighlightColor"]));
            }
            set {
                this["StashTabOverlayHighlightColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int StashTabOverlayHighlightMode {
            get {
                return ((int)(this["StashTabOverlayHighlightMode"]));
            }
            set {
                this["StashTabOverlayHighlightMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double StashTabOverlayIndividualTabMargin {
            get {
                return ((double)(this["StashTabOverlayIndividualTabMargin"]));
            }
            set {
                this["StashTabOverlayIndividualTabMargin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double StashTabOverlayIndividualTabHeaderPadding {
            get {
                return ((double)(this["StashTabOverlayIndividualTabHeaderPadding"]));
            }
            set {
                this["StashTabOverlayIndividualTabHeaderPadding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double StashTabOverlayIndividualTabHeaderGap {
            get {
                return ((double)(this["StashTabOverlayIndividualTabHeaderGap"]));
            }
            set {
                this["StashTabOverlayIndividualTabHeaderGap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LootFilterManipulationEnabled {
            get {
                return ((bool)(this["LootFilterManipulationEnabled"]));
            }
            set {
                this["LootFilterManipulationEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LootFilterFileLocation {
            get {
                return ((string)(this["LootFilterFileLocation"]));
            }
            set {
                this["LootFilterFileLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LootFilterIconsEnabled {
            get {
                return ((bool)(this["LootFilterIconsEnabled"]));
            }
            set {
                this["LootFilterIconsEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF0303")]
        public string LootFilterRingColor {
            get {
                return ((string)(this["LootFilterRingColor"]));
            }
            set {
                this["LootFilterRingColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF0303")]
        public string LootFilterAmuletColor {
            get {
                return ((string)(this["LootFilterAmuletColor"]));
            }
            set {
                this["LootFilterAmuletColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF0303")]
        public string LootFilterBeltColor {
            get {
                return ((string)(this["LootFilterBeltColor"]));
            }
            set {
                this["LootFilterBeltColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF0018FF")]
        public string LootFilterBootsColor {
            get {
                return ((string)(this["LootFilterBootsColor"]));
            }
            set {
                this["LootFilterBootsColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF04FF00")]
        public string LootFilterGlovesColor {
            get {
                return ((string)(this["LootFilterGlovesColor"]));
            }
            set {
                this["LootFilterGlovesColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFF8FF04")]
        public string LootFilterHelmetColor {
            get {
                return ((string)(this["LootFilterHelmetColor"]));
            }
            set {
                this["LootFilterHelmetColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFDD00FF")]
        public string LootFilterBodyArmourColor {
            get {
                return ((string)(this["LootFilterBodyArmourColor"]));
            }
            set {
                this["LootFilterBodyArmourColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF00DCFF")]
        public string LootFilterWeaponColor {
            get {
                return ((string)(this["LootFilterWeaponColor"]));
            }
            set {
                this["LootFilterWeaponColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LootFilterRingsAlwaysActive {
            get {
                return ((bool)(this["LootFilterRingsAlwaysActive"]));
            }
            set {
                this["LootFilterRingsAlwaysActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LootFilterAmuletsAlwaysActive {
            get {
                return ((bool)(this["LootFilterAmuletsAlwaysActive"]));
            }
            set {
                this["LootFilterAmuletsAlwaysActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LootFilterBeltsAlwaysActive {
            get {
                return ((bool)(this["LootFilterBeltsAlwaysActive"]));
            }
            set {
                this["LootFilterBeltsAlwaysActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LootFilterBootsAlwaysActive {
            get {
                return ((bool)(this["LootFilterBootsAlwaysActive"]));
            }
            set {
                this["LootFilterBootsAlwaysActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LootFilterGlovesAlwaysActive {
            get {
                return ((bool)(this["LootFilterGlovesAlwaysActive"]));
            }
            set {
                this["LootFilterGlovesAlwaysActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LootFilterHelmetsAlwaysActive {
            get {
                return ((bool)(this["LootFilterHelmetsAlwaysActive"]));
            }
            set {
                this["LootFilterHelmetsAlwaysActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LootFilterBodyArmourAlwaysActive {
            get {
                return ((bool)(this["LootFilterBodyArmourAlwaysActive"]));
            }
            set {
                this["LootFilterBodyArmourAlwaysActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LootFilterWeaponsAlwaysActive {
            get {
                return ((bool)(this["LootFilterWeaponsAlwaysActive"]));
            }
            set {
                this["LootFilterWeaponsAlwaysActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DoNotPreserveLowItemLevelGear {
            get {
                return ((bool)(this["DoNotPreserveLowItemLevelGear"]));
            }
            set {
                this["DoNotPreserveLowItemLevelGear"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Language {
            get {
                return ((int)(this["Language"]));
            }
            set {
                this["Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CloseToTrayEnabled {
            get {
                return ((bool)(this["CloseToTrayEnabled"]));
            }
            set {
                this["CloseToTrayEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double SettingsWindowTopPosition {
            get {
                return ((double)(this["SettingsWindowTopPosition"]));
            }
            set {
                this["SettingsWindowTopPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double SettingsWindowLeftPosition {
            get {
                return ((double)(this["SettingsWindowLeftPosition"]));
            }
            set {
                this["SettingsWindowLeftPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double SetTrackerOverlayTopPosition {
            get {
                return ((double)(this["SetTrackerOverlayTopPosition"]));
            }
            set {
                this["SetTrackerOverlayTopPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double SetTrackerOverlayLeftPosition {
            get {
                return ((double)(this["SetTrackerOverlayLeftPosition"]));
            }
            set {
                this["SetTrackerOverlayLeftPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("74")]
        public double StashTabOverlayTopPosition {
            get {
                return ((double)(this["StashTabOverlayTopPosition"]));
            }
            set {
                this["StashTabOverlayTopPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public double StashTabOverlayLeftPosition {
            get {
                return ((double)(this["StashTabOverlayLeftPosition"]));
            }
            set {
                this["StashTabOverlayLeftPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("690")]
        public double StashTabOverlayHeight {
            get {
                return ((double)(this["StashTabOverlayHeight"]));
            }
            set {
                this["StashTabOverlayHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("641")]
        public double StashTabOverlayWidth {
            get {
                return ((double)(this["StashTabOverlayWidth"]));
            }
            set {
                this["StashTabOverlayWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DebugMode {
            get {
                return ((bool)(this["DebugMode"]));
            }
            set {
                this["DebugMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpgradeSettingsAfterUpdate {
            get {
                return ((bool)(this["UpgradeSettingsAfterUpdate"]));
            }
            set {
                this["UpgradeSettingsAfterUpdate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime PathOfExileApiAuthTokenExpiration {
            get {
                return ((global::System.DateTime)(this["PathOfExileApiAuthTokenExpiration"]));
            }
            set {
                this["PathOfExileApiAuthTokenExpiration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PathOfExileApiAuthToken {
            get {
                return ((string)(this["PathOfExileApiAuthToken"]));
            }
            set {
                this["PathOfExileApiAuthToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VendorSetsEarly {
            get {
                return ((bool)(this["VendorSetsEarly"]));
            }
            set {
                this["VendorSetsEarly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("< not set >")]
        public string FetchStashHotkey {
            get {
                return ((string)(this["FetchStashHotkey"]));
            }
            set {
                this["FetchStashHotkey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("< not set >")]
        public string ToggleSetTrackerOverlayHotkey {
            get {
                return ((string)(this["ToggleSetTrackerOverlayHotkey"]));
            }
            set {
                this["ToggleSetTrackerOverlayHotkey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("< not set >")]
        public string ToggleStashTabOverlayHotkey {
            get {
                return ((string)(this["ToggleStashTabOverlayHotkey"]));
            }
            set {
                this["ToggleStashTabOverlayHotkey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SettingsWindowNavIndex {
            get {
                return ((int)(this["SettingsWindowNavIndex"]));
            }
            set {
                this["SettingsWindowNavIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("< not set >")]
        public string ReloadFilterHotkey {
            get {
                return ((string)(this["ReloadFilterHotkey"]));
            }
            set {
                this["ReloadFilterHotkey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SilenceNeedItemsMessage {
            get {
                return ((bool)(this["SilenceNeedItemsMessage"]));
            }
            set {
                this["SilenceNeedItemsMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SilenceSetsFullMessage {
            get {
                return ((bool)(this["SilenceSetsFullMessage"]));
            }
            set {
                this["SilenceSetsFullMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int PathOfExileClientLogLocationMode {
            get {
                return ((int)(this["PathOfExileClientLogLocationMode"]));
            }
            set {
                this["PathOfExileClientLogLocationMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SoundEnabled {
            get {
                return ((bool)(this["SoundEnabled"]));
            }
            set {
                this["SoundEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double SoundLevel {
            get {
                return ((double)(this["SoundLevel"]));
            }
            set {
                this["SoundLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StashTabIdentifiers {
            get {
                return ((string)(this["StashTabIdentifiers"]));
            }
            set {
                this["StashTabIdentifiers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#00000000")]
        public string StashTabOverlayTabDefaultBackgroundColor {
            get {
                return ((string)(this["StashTabOverlayTabDefaultBackgroundColor"]));
            }
            set {
                this["StashTabOverlayTabDefaultBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double StashTabOverlayTabGroupBottomMargin {
            get {
                return ((double)(this["StashTabOverlayTabGroupBottomMargin"]));
            }
            set {
                this["StashTabOverlayTabGroupBottomMargin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float StashTabOverlayTabOpacity {
            get {
                return ((float)(this["StashTabOverlayTabOpacity"]));
            }
            set {
                this["StashTabOverlayTabOpacity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime RateLimitExpiresOn {
            get {
                return ((global::System.DateTime)(this["RateLimitExpiresOn"]));
            }
            set {
                this["RateLimitExpiresOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CustomLeagueEnabled {
            get {
                return ((bool)(this["CustomLeagueEnabled"]));
            }
            set {
                this["CustomLeagueEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LegacyAuthMode {
            get {
                return ((bool)(this["LegacyAuthMode"]));
            }
            set {
                this["LegacyAuthMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LegacyAuthAccountName {
            get {
                return ((string)(this["LegacyAuthAccountName"]));
            }
            set {
                this["LegacyAuthAccountName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LegacyAuthSessionId {
            get {
                return ((string)(this["LegacyAuthSessionId"]));
            }
            set {
                this["LegacyAuthSessionId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GuildStashMode {
            get {
                return ((bool)(this["GuildStashMode"]));
            }
            set {
                this["GuildStashMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HideRemoveOnlyTabs {
            get {
                return ((bool)(this["HideRemoveOnlyTabs"]));
            }
            set {
                this["HideRemoveOnlyTabs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LootFilterSpaceSavingHideLargeWeapons {
            get {
                return ((bool)(this["LootFilterSpaceSavingHideLargeWeapons"]));
            }
            set {
                this["LootFilterSpaceSavingHideLargeWeapons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LootFilterSpaceSavingHideOffHand {
            get {
                return ((bool)(this["LootFilterSpaceSavingHideOffHand"]));
            }
            set {
                this["LootFilterSpaceSavingHideOffHand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFFFF")]
        public string LootFilterStylesRingTextColor {
            get {
                return ((string)(this["LootFilterStylesRingTextColor"]));
            }
            set {
                this["LootFilterStylesRingTextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFFFF")]
        public string LootFilterStylesRingBorderColor {
            get {
                return ((string)(this["LootFilterStylesRingBorderColor"]));
            }
            set {
                this["LootFilterStylesRingBorderColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF0000")]
        public string LootFilterStylesRingBackgroundColor {
            get {
                return ((string)(this["LootFilterStylesRingBackgroundColor"]));
            }
            set {
                this["LootFilterStylesRingBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LootFilterStylesRingAlwaysActive {
            get {
                return ((bool)(this["LootFilterStylesRingAlwaysActive"]));
            }
            set {
                this["LootFilterStylesRingAlwaysActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LootFilterStylesRingAlwaysDisabled {
            get {
                return ((bool)(this["LootFilterStylesRingAlwaysDisabled"]));
            }
            set {
                this["LootFilterStylesRingAlwaysDisabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LootFilterStylesRingMapIconEnabled {
            get {
                return ((bool)(this["LootFilterStylesRingMapIconEnabled"]));
            }
            set {
                this["LootFilterStylesRingMapIconEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int LootFilterStylesRingMapIconColor {
            get {
                return ((int)(this["LootFilterStylesRingMapIconColor"]));
            }
            set {
                this["LootFilterStylesRingMapIconColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LootFilterStylesRingMapIconSize {
            get {
                return ((int)(this["LootFilterStylesRingMapIconSize"]));
            }
            set {
                this["LootFilterStylesRingMapIconSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LootFilterStylesRingMapIconShape {
            get {
                return ((int)(this["LootFilterStylesRingMapIconShape"]));
            }
            set {
                this["LootFilterStylesRingMapIconShape"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LootFilterStylesRingBeamEnabled {
            get {
                return ((bool)(this["LootFilterStylesRingBeamEnabled"]));
            }
            set {
                this["LootFilterStylesRingBeamEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LootFilterStylesRingBeamTemporary {
            get {
                return ((bool)(this["LootFilterStylesRingBeamTemporary"]));
            }
            set {
                this["LootFilterStylesRingBeamTemporary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int LootFilterStylesRingBeamColor {
            get {
                return ((int)(this["LootFilterStylesRingBeamColor"]));
            }
            set {
                this["LootFilterStylesRingBeamColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int LootFilterStylesRingTextFontSize {
            get {
                return ((int)(this["LootFilterStylesRingTextFontSize"]));
            }
            set {
                this["LootFilterStylesRingTextFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LootFilterStylesRingTextColorEnabled {
            get {
                return ((bool)(this["LootFilterStylesRingTextColorEnabled"]));
            }
            set {
                this["LootFilterStylesRingTextColorEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LootFilterStylesRingBorderColorEnabled {
            get {
                return ((bool)(this["LootFilterStylesRingBorderColorEnabled"]));
            }
            set {
                this["LootFilterStylesRingBorderColorEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LootFilterStylesRingBackgroundColorEnabled {
            get {
                return ((bool)(this["LootFilterStylesRingBackgroundColorEnabled"]));
            }
            set {
                this["LootFilterStylesRingBackgroundColorEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFFFF")]
        public string LootFilterStylesAmuletTextColor {
            get {
                return ((string)(this["LootFilterStylesAmuletTextColor"]));
            }
            set {
                this["LootFilterStylesAmuletTextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFFFF")]
        public string LootFilterStylesAmuletBorderColor {
            get {
                return ((string)(this["LootFilterStylesAmuletBorderColor"]));
            }
            set {
                this["LootFilterStylesAmuletBorderColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF0000")]
        public string LootFilterStylesAmuletBackgroundColor {
            get {
                return ((string)(this["LootFilterStylesAmuletBackgroundColor"]));
            }
            set {
                this["LootFilterStylesAmuletBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LootFilterStylesAmuletAlwaysActive {
            get {
                return ((bool)(this["LootFilterStylesAmuletAlwaysActive"]));
            }
            set {
                this["LootFilterStylesAmuletAlwaysActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LootFilterStylesAmuletAlwaysDisabled {
            get {
                return ((bool)(this["LootFilterStylesAmuletAlwaysDisabled"]));
            }
            set {
                this["LootFilterStylesAmuletAlwaysDisabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LootFilterStylesAmuletMapIconEnabled {
            get {
                return ((bool)(this["LootFilterStylesAmuletMapIconEnabled"]));
            }
            set {
                this["LootFilterStylesAmuletMapIconEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int LootFilterStylesAmuletMapIconColor {
            get {
                return ((int)(this["LootFilterStylesAmuletMapIconColor"]));
            }
            set {
                this["LootFilterStylesAmuletMapIconColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LootFilterStylesAmuletMapIconSize {
            get {
                return ((int)(this["LootFilterStylesAmuletMapIconSize"]));
            }
            set {
                this["LootFilterStylesAmuletMapIconSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LootFilterStylesAmuletMapIconShape {
            get {
                return ((int)(this["LootFilterStylesAmuletMapIconShape"]));
            }
            set {
                this["LootFilterStylesAmuletMapIconShape"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LootFilterStylesAmuletBeamEnabled {
            get {
                return ((bool)(this["LootFilterStylesAmuletBeamEnabled"]));
            }
            set {
                this["LootFilterStylesAmuletBeamEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LootFilterStylesAmuletBeamTemporary {
            get {
                return ((bool)(this["LootFilterStylesAmuletBeamTemporary"]));
            }
            set {
                this["LootFilterStylesAmuletBeamTemporary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int LootFilterStylesAmuletBeamColor {
            get {
                return ((int)(this["LootFilterStylesAmuletBeamColor"]));
            }
            set {
                this["LootFilterStylesAmuletBeamColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int LootFilterStylesAmuletTextFontSize {
            get {
                return ((int)(this["LootFilterStylesAmuletTextFontSize"]));
            }
            set {
                this["LootFilterStylesAmuletTextFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LootFilterStylesAmuletTextColorEnabled {
            get {
                return ((bool)(this["LootFilterStylesAmuletTextColorEnabled"]));
            }
            set {
                this["LootFilterStylesAmuletTextColorEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LootFilterStylesAmuletBorderColorEnabled {
            get {
                return ((bool)(this["LootFilterStylesAmuletBorderColorEnabled"]));
            }
            set {
                this["LootFilterStylesAmuletBorderColorEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LootFilterStylesAmuletBackgroundColorEnabled {
            get {
                return ((bool)(this["LootFilterStylesAmuletBackgroundColorEnabled"]));
            }
            set {
                this["LootFilterStylesAmuletBackgroundColorEnabled"] = value;
            }
        }
    }
}
